spring:
  application.name: yupj-backend-service-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
        heart-beat-interval: 5 # 设置心跳间隔时间

    loadbalancer:
      ribbon:
        enabled: false
      nacos:
        enabled: true
server:
  address: 0.0.0.0